@startuml

[*] --> WAIT_FIRST_COIN

WAIT_FIRST_COIN:  dispense_beverage = '0'\nreturn_coin = '0'
DISPENSE_PAID_1:  dispense_beverage = '1'\nreturn_coin = '0'
WAIT_SECOND_COIN: dispense_beverage = '0'\nreturn_coin = '0'
DISPENSE_PAID_2:  dispense_beverage = '1'\nreturn_coin = '0'
WAIT_FREE_COIN:   dispense_beverage = '0'\nreturn_coin = '0'
DISPENSE_FREE:    dispense_beverage = '1'\nreturn_coin = '1'

WAIT_FIRST_COIN --> DISPENSE_PAID_1 : coin_inserted = '1'
WAIT_FIRST_COIN --> WAIT_FIRST_COIN : coin_inserted = '0'

DISPENSE_PAID_1 --> WAIT_SECOND_COIN

WAIT_SECOND_COIN --> DISPENSE_PAID_2 : coin_inserted = '1'
WAIT_SECOND_COIN --> WAIT_SECOND_COIN : coin_inserted = '0'

DISPENSE_PAID_2 --> WAIT_FREE_COIN

WAIT_FREE_COIN --> DISPENSE_FREE : coin_inserted = '1'
WAIT_FREE_COIN --> WAIT_FREE_COIN : coin_inserted = '0'

DISPENSE_FREE --> WAIT_FIRST_COIN

@enduml